<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="1" failed="0" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[ Create Request to get response ]]>
    </line>
    <line>
      <![CDATA[Status Code: 400]]>
    </line>
    <line>
      <![CDATA[Validate Invalid range error]]>
    </line>
  </reporter-output>
  <suite started-at="2020-06-02T06:09:49Z" name="Default suite" finished-at="2020-06-02T06:09:51Z" duration-ms="2472">
    <groups>
    </groups>
    <test started-at="2020-06-02T06:09:49Z" name="Default test" finished-at="2020-06-02T06:09:51Z" duration-ms="2472">
      <class name="com.atmecs.api.get.testscripts.noauth.googleapibooks.TC_04_Get_Test_InValid_Range_Error">
        <test-method signature="GetInvalidRangeError()[pri:0, instance:com.atmecs.api.get.testscripts.noauth.googleapibooks.TC_04_Get_Test_InValid_Range_Error@6a03bcb1]" started-at="2020-06-02T06:09:49Z" name="GetInvalidRangeError" finished-at="2020-06-02T06:09:51Z" duration-ms="2437" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[ Create Request to get response ]]>
            </line>
            <line>
              <![CDATA[Status Code: 400]]>
            </line>
            <line>
              <![CDATA[Validate Invalid range error]]>
            </line>
          </reporter-output>
        </test-method> <!-- GetInvalidRangeError -->
      </class> <!-- com.atmecs.api.get.testscripts.noauth.googleapibooks.TC_04_Get_Test_InValid_Range_Error -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
